runtime: nodejs12
service: tournament
handlers:
  - url: /css/(.*)
    static_files: dist/css/\1
    upload: dist/css/(.*)
    secure: always
  - url: /img/(.*)
    static_files: dist/img/\1
    upload: dist/img/(.*)
    secure: always
  - url: /js/(.*)
    static_files: dist/js/\1
    upload: dist/js/(.*)
    secure: always
  - url: /media/(.*)
    static_files: dist/media/\1
    upload: dist/media/(.*)
    secure: always
  - url: /(.*\..*)
    static_files: dist/\1
    upload: dist/(.*\..*)
    secure: always
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

manual_scaling:
  instances: 1

